<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Administrateur {


	/**
	 * @access public
	 * @param News $_oNewsArg 
	 */

	public final  function AdministrateurAjoute(News $_oNewsArg) {

	}


	/**
	 * @access public
	 * @param News $_oNewsArg 
	 */

	public final  function AdministrateurSupprime(News $_oNewsArg) {

	}


}
?>