<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class News {

	/**
	 * 
	 * @var int
	 * @access protected
	 */
	protected  $_id;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $_auteur;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $_titre;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $_contenu;

	/**
	 * 
	 * @var int
	 * @access protected
	 */
	protected  $_dateAjout;

	/**
	 * 
	 * @var int
	 * @access protected
	 */
	protected  $_dateModif;


	/**
	 * @access public
	 */

	public final  function __construct() {

	}


	/**
	 * @access public
	 * @param array $_aDonneeArg 
	 */

	public final  function hydrate($_aDonneeArg) {

	}


	/**
	 * @access public
	 * @param int $_iIdArg 
	 */

	public final  function setId($_iIdArg) {

	}


	/**
	 * @access public
	 */

	public final  function getId() {

	}


	/**
	 * @access public
	 * @param string $_sAuteurArg 
	 */

	public final  function setAuteur($_sAuteurArg) {

	}


	/**
	 * @access public
	 */

	public final  function getAuteur() {

	}


	/**
	 * @access public
	 * @param string $_sTitreArg 
	 */

	public final  function setTitre($_sTitreArg) {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function getTitre() {

	}


	/**
	 * @access public
	 * @param string $_sContenuArg 
	 */

	public final  function setContenu($_sContenuArg) {

	}


	/**
	 * @access public
	 */

	public final  function getContenu() {

	}


	/**
	 * @access public
	 * @param DateTime $_DateTimeArg 
	 */

	public final  function setDateAjout(DateTime $_DateTimeArg) {

	}


	/**
	 * @access public
	 */

	public final  function getDateAjout() {

	}


	/**
	 * @access public
	 * @param DateTime $_DateModifArg 
	 */

	public final  function setDateModif(DateTime $_DateModifArg) {

	}


	/**
	 * @access public
	 */

	public final  function getDateModif() {

	}


	/**
	 * @access public
	 * @param uint $_iNumberOfNewsArg 
	 */

	public final  function getNLastNews(uint $_iNumberOfNewsArg) {

	}


}
?>