<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class NewsManager {

	/**
	 * 
	 * @var 
	 * @access protected
	 */
	protected  $_db;


	/**
	 * @access public
	 * @param PDO $_dbArg 
	 */

	public final  function __construct(PDO $_dbArg) {
		this->_db = $_dbArg;
	}


	/**
	 * @access public
	 * @param News $_oNewsArg 
	 */

	public final  function add(News $_oNewsArg) {

	}


	/**
	 * @access public
	 * @param News $_oNewsArg 
	 */

	public final  function delete(News $_oNewsArg) {

	}


	/**
	 * @access public
	 * @param unsigned int $_uiIdArg 
	 */

	public final  function get(unsigned int $_uiIdArg) {

	}


	/**
	 * @access public
	 */

	public final  function getList() {

    $q = $this->_db->query('SELECT id, auteur, titre, contenu, dateAjout, dateModif FROM news ORDER BY dateAjout LIMIT 0, 5');


    $q->setFetchMode(PDO::FETCH_CLASS, 'News');


    return $News = $q->fetchAll();
	}


}
?>